server:
  port: 8080
  mode: debug

database:
  host: db
  port: 3306
  user: root
  password: 123456
  dbname: herb_recognition
  charset: utf8mb4
  parseTime: true
  loc: Local

# 识别模块地址
model_service:
  url: "http://inference:5001"
